services:
  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - data-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  data-db: